package com.Protronserver.Protronserver.Controller;

import com.Protronserver.Protronserver.Entities.*;
import com.Protronserver.Protronserver.Service.*;
import com.Protronserver.Protronserver.DTOs.*;
import com.Protronserver.Protronserver.Utils.LoggedInUserUtils;
import com.Protronserver.Protronserver.Entities.SystemMaster;
import com.Protronserver.Protronserver.Service.BudgetDocumentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * REST Controller for Budget Line operations
 */
@RestController
@RequestMapping("/api/budget-lines")

public class BudgetLineController {

    @Autowired
    private BudgetLineService budgetLineService;

    @Autowired
    private BudgetAllocationService budgetAllocationService;

    @Autowired
    private LoggedInUserUtils loggedInUserUtils;

    @Autowired
    private SystemMasterService systemMasterService;

    @Autowired
    private BudgetDocumentService budgetDocumentService;

    /**
     * Add a new budget line item
     */
    @PostMapping
    public ResponseEntity<?> addBudgetLine(@Valid @RequestBody BudgetLineRequest request) {
        try {
            // Validate amount approved against allocations if provided
            if (request.getAllocations() != null && !request.getAllocations().isEmpty()) {
                BigDecimal totalAllocationAmount = request.getAllocations().stream()
                        .map(allocation -> allocation.getAmount())
                        .reduce(BigDecimal.ZERO, BigDecimal::add);

                if (request.getAmountApproved().compareTo(totalAllocationAmount) < 0) {
                    return ResponseEntity.badRequest()
                            .body("Error: Amount approved (" + request.getAmountApproved() +
                                    ") cannot be less than total allocation amount (" + totalAllocationAmount + ")");
                }
            }

            // Create budget line entity (don't set budgetId - let JPA auto-generate it)
            BudgetLine budgetLine = new BudgetLine();
            // budgetId will be auto-generated by JPA

            // Automatically set tenant ID from logged-in user (same as project module)
            String currentTenantId = loggedInUserUtils.getLoggedInUser().getTenant().getTenantId().toString();
            budgetLine.setTenantId(currentTenantId);

            budgetLine.setBudgetName(request.getBudgetName());
            budgetLine.setBudgetDescription(request.getBudgetDescription());
            budgetLine.setBudgetLineItem(request.getBudgetLineItem());
            budgetLine.setBudgetEndDate(request.getBudgetEndDate());
            budgetLine.setBudgetOwner(request.getBudgetOwner());
            budgetLine.setSponsor(request.getSponsor());
            budgetLine.setLob(request.getLob());
            budgetLine.setCurrency(request.getCurrency());
            budgetLine.setAmountApproved(request.getAmountApproved());
            budgetLine.setAmountUtilized(request.getAmountUtilized());
            budgetLine.setAmountAvailable(request.getAmountAvailable());
            budgetLine.setRemarks(request.getRemarks());
            budgetLine.setStartTimestamp(LocalDateTime.now());
            budgetLine.setLastUpdatedBy(request.getLastUpdatedBy());
            budgetLine.setAttachment(request.getAttachment());

            // Save budget line
            BudgetLine savedBudgetLine = budgetLineService.save(budgetLine);

            // Save allocations if provided
            if (request.getAllocations() != null) {
                for (BudgetLineAllocationRequest allocationRequest : request.getAllocations()) {
                    BudgetAllocation allocation = new BudgetAllocation();
                    allocation.setBudgetLine(savedBudgetLine);
                    allocation.setTenantId(currentTenantId);
                    allocation.setVendorName(allocationRequest.getVendorName());
                    allocation.setAmount(allocationRequest.getAmount());
                    allocation.setRemarks(allocationRequest.getRemarks());

                    // Handle system - either from SystemMaster or custom system name
                    if (allocationRequest.getSystemId() != null) {
                        // Use existing system from SystemMaster
                        SystemMaster system = systemMasterService.getSystemById(allocationRequest.getSystemId());
                        if (system != null) {
                            allocation.setSystem(system);
                            allocation.setSystemName(system.getSystemName());
                        } else {
                            allocation.setSystemName(allocationRequest.getSystemName());
                        }
                    } else if (allocationRequest.getSystemName() != null
                            && !allocationRequest.getSystemName().trim().isEmpty()) {
                        // Use custom system name
                        allocation.setSystemName(allocationRequest.getSystemName().trim());
                    }

                    budgetAllocationService.save(allocation);
                }
            }

            BudgetLineResponse response = convertToResponse(savedBudgetLine);
            return ResponseEntity.status(HttpStatus.CREATED).body(response);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error creating budget line: " + e.getMessage());
        }
    }

    /**
     * Edit an existing budget line item
     */
    @PutMapping("/{budgetId}")
    public ResponseEntity<?> editBudgetLine(@PathVariable Integer budgetId,
            @Valid @RequestBody BudgetLineRequest request) {
        try {
            Optional<BudgetLine> existingBudgetLineOpt = budgetLineService.findById(budgetId);

            if (!existingBudgetLineOpt.isPresent()) {
                return ResponseEntity.notFound().build();
            }

            BudgetLine existingBudgetLine = existingBudgetLineOpt.get();

            // Get existing allocations for this budget line
            List<BudgetAllocation> existingAllocations = budgetAllocationService.findByBudgetLineId(budgetId);

            // Calculate total allocation amount (existing + new)
            BigDecimal totalAllocationAmount = BigDecimal.ZERO;

            // Add existing allocations that are not being updated
            for (BudgetAllocation existingAllocation : existingAllocations) {
                totalAllocationAmount = totalAllocationAmount.add(existingAllocation.getAmount());
            }

            // Add new allocations if provided in request
            if (request.getAllocations() != null && !request.getAllocations().isEmpty()) {
                BigDecimal newAllocationsTotal = request.getAllocations().stream()
                        .map(allocation -> allocation.getAmount())
                        .reduce(BigDecimal.ZERO, BigDecimal::add);
                totalAllocationAmount = totalAllocationAmount.add(newAllocationsTotal);
            }

            // Validate amount approved against total allocations
            if (totalAllocationAmount.compareTo(BigDecimal.ZERO) > 0 &&
                    request.getAmountApproved().compareTo(totalAllocationAmount) < 0) {
                return ResponseEntity.badRequest()
                        .body("Error: Amount approved (" + request.getAmountApproved() +
                                ") cannot be less than total allocation amount (" + totalAllocationAmount + ")");
            }

            // Update budget line fields
            // Automatically set tenant ID from logged-in user (same as project module)
            String currentTenantId = loggedInUserUtils.getLoggedInUser().getTenant().getTenantId().toString();
            existingBudgetLine.setTenantId(currentTenantId);

            existingBudgetLine.setBudgetName(request.getBudgetName());
            existingBudgetLine.setBudgetDescription(request.getBudgetDescription());
            existingBudgetLine.setBudgetLineItem(request.getBudgetLineItem());
            existingBudgetLine.setBudgetEndDate(request.getBudgetEndDate());
            existingBudgetLine.setBudgetOwner(request.getBudgetOwner());
            existingBudgetLine.setSponsor(request.getSponsor());
            existingBudgetLine.setLob(request.getLob());
            existingBudgetLine.setCurrency(request.getCurrency());
            existingBudgetLine.setAmountApproved(request.getAmountApproved());
            existingBudgetLine.setAmountUtilized(request.getAmountUtilized());
            existingBudgetLine.setAmountAvailable(request.getAmountAvailable());
            existingBudgetLine.setRemarks(request.getRemarks());
            existingBudgetLine.setEndTimestamp(LocalDateTime.now());
            existingBudgetLine.setLastUpdatedBy(request.getLastUpdatedBy());

            if (request.getAttachment() != null) {
                existingBudgetLine.setAttachment(request.getAttachment());
            }

            // Save updated budget line
            BudgetLine updatedBudgetLine = budgetLineService.save(existingBudgetLine);

            // Save new allocations if provided
            if (request.getAllocations() != null) {
                for (BudgetLineAllocationRequest allocationRequest : request.getAllocations()) {
                    BudgetAllocation allocation = new BudgetAllocation();
                    allocation.setBudgetLine(updatedBudgetLine);
                    allocation.setTenantId(currentTenantId);
                    allocation.setVendorName(allocationRequest.getVendorName());
                    allocation.setAmount(allocationRequest.getAmount());
                    allocation.setRemarks(allocationRequest.getRemarks());

                    // Handle system - either from SystemMaster or custom system name
                    if (allocationRequest.getSystemId() != null) {
                        // Use existing system from SystemMaster
                        SystemMaster system = systemMasterService.getSystemById(allocationRequest.getSystemId());
                        if (system != null) {
                            allocation.setSystem(system);
                            allocation.setSystemName(system.getSystemName());
                        } else {
                            allocation.setSystemName(allocationRequest.getSystemName());
                        }
                    } else if (allocationRequest.getSystemName() != null
                            && !allocationRequest.getSystemName().trim().isEmpty()) {
                        // Use custom system name
                        allocation.setSystemName(allocationRequest.getSystemName().trim());
                    }

                    budgetAllocationService.save(allocation);
                }
            }

            BudgetLineResponse response = convertToResponse(updatedBudgetLine);
            return ResponseEntity.ok(response);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error updating budget line: " + e.getMessage());
        }
    }

    /**
     * Get budget line by ID
     */
    @GetMapping("/{budgetId}")
    public ResponseEntity<?> getBudgetLine(@PathVariable Integer budgetId) {
        try {
            Optional<BudgetLine> budgetLineOpt = budgetLineService.findById(budgetId);

            if (!budgetLineOpt.isPresent()) {
                return ResponseEntity.notFound().build();
            }

            BudgetLineResponse response = convertToResponse(budgetLineOpt.get());
            return ResponseEntity.ok(response);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error retrieving budget line: " + e.getMessage());
        }
    }

    /**
     * Get all budget lines
     */
    @GetMapping
    public ResponseEntity<?> getAllBudgetLines() {
        try {
            List<BudgetLine> budgetLines = budgetLineService.findAll();
            List<BudgetLineResponse> responses = budgetLines.stream()
                    .map(this::convertToResponse)
                    .collect(java.util.stream.Collectors.toList());

            return ResponseEntity.ok(responses);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error retrieving budget lines: " + e.getMessage());
        }
    }

    /**
     * Get budget lines by tenant ID
     */
    @GetMapping("/tenant/{tenantId}")
    public ResponseEntity<?> getBudgetLinesByTenant(@PathVariable String tenantId) {
        try {
            List<BudgetLine> budgetLines = budgetLineService.findByTenantId(tenantId);
            List<BudgetLineResponse> responses = budgetLines.stream()
                    .map(this::convertToResponse)
                    .collect(java.util.stream.Collectors.toList());

            return ResponseEntity.ok(responses);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error retrieving budget lines by tenant: " + e.getMessage());
        }
    }

    /**
     * Get budget lines by budget owner
     */
    @GetMapping("/owner/{budgetOwner}")
    public ResponseEntity<?> getBudgetLinesByOwner(@PathVariable String budgetOwner) {
        try {
            List<BudgetLine> budgetLines = budgetLineService.findByBudgetOwner(budgetOwner);
            List<BudgetLineResponse> responses = budgetLines.stream()
                    .map(this::convertToResponse)
                    .collect(java.util.stream.Collectors.toList());

            return ResponseEntity.ok(responses);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error retrieving budget lines by owner: " + e.getMessage());
        }
    }

    /**
     * Delete budget line by ID
     */
    @DeleteMapping("/{budgetId}")
    public ResponseEntity<?> deleteBudgetLine(@PathVariable Integer budgetId) {
        try {
            Optional<BudgetLine> budgetLineOpt = budgetLineService.findById(budgetId);

            if (!budgetLineOpt.isPresent()) {
                return ResponseEntity.notFound().build();
            }

            // Delete associated allocations first
            budgetAllocationService.deleteByBudgetLineId(budgetId);

            // Delete associated documents first
            budgetDocumentService.deleteDocumentsByBudgetId(budgetId);

            // Delete budget line
            budgetLineService.delete(budgetId);

            return ResponseEntity.ok("Budget line deleted successfully");

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error deleting budget line: " + e.getMessage());
        }
    }

    /**
     * Convert BudgetLine entity to response DTO
     */
    private BudgetLineResponse convertToResponse(BudgetLine budgetLine) {
        BudgetLineResponse response = new BudgetLineResponse();
        response.setBudgetId(budgetLine.getBudgetId());
        response.setTenantId(budgetLine.getTenantId());
        response.setBudgetName(budgetLine.getBudgetName());
        response.setBudgetDescription(budgetLine.getBudgetDescription());
        response.setBudgetLineItem(budgetLine.getBudgetLineItem());
        response.setBudgetEndDate(budgetLine.getBudgetEndDate());
        response.setBudgetOwner(budgetLine.getBudgetOwner());
        response.setSponsor(budgetLine.getSponsor());
        response.setLob(budgetLine.getLob());
        response.setCurrency(budgetLine.getCurrency());
        response.setAmountApproved(budgetLine.getAmountApproved());
        response.setAmountUtilized(budgetLine.getAmountUtilized());
        response.setAmountAvailable(budgetLine.getAmountAvailable());
        response.setRemarks(budgetLine.getRemarks());
        response.setStartTimestamp(budgetLine.getStartTimestamp());
        response.setEndTimestamp(budgetLine.getEndTimestamp());
        response.setLastUpdatedBy(budgetLine.getLastUpdatedBy());
        response.setHasAttachment(budgetLine.getAttachment() != null && budgetLine.getAttachment().length > 0);

        // Get allocations for this budget line - convert to DTOs to avoid lazy loading
        // issues
        List<BudgetAllocation> allocations = budgetAllocationService.findByBudgetLineId(budgetLine.getBudgetId());

        // Convert allocations to simple DTOs to avoid lazy loading issues
        List<BudgetAllocationResponse> allocationDTOs = allocations.stream()
                .map(allocation -> {
                    BudgetAllocationResponse allocationDTO = new BudgetAllocationResponse();
                    allocationDTO.setAllocationId(allocation.getAllocationId());
                    allocationDTO.setBudgetLineId(allocation.getBudgetLine().getBudgetId());
                    allocationDTO.setBudgetLineName(allocation.getBudgetLine().getBudgetName());
                    allocationDTO.setTenantId(allocation.getTenantId());
                    allocationDTO.setVendorName(allocation.getVendorName());
                    allocationDTO.setSystemName(allocation.getSystemName() != null ? allocation.getSystemName()
                            : (allocation.getSystem() != null ? allocation.getSystem().getSystemName() : null));
                    allocationDTO.setAmount(allocation.getAmount());
                    allocationDTO.setRemarks(allocation.getRemarks());
                    return allocationDTO;
                })
                .collect(java.util.stream.Collectors.toList());

        response.setAllocations(allocationDTOs);

        return response;
    }
}